Contrib issue 632
mviewer/mviewer pull request #743
Opened 2023-04-07 13:40 UTC by bdavid-rennesmetrpole

Démo publique correspondant à l'issue https://github.com/mviewer/mviewer/issues/632

2023-04-07 13:44 UTC, Gaetanbrl commented
Bonjour @bdavid-rennesmetrpole 
Cette PR me semble contenir des modifications déjà présentes dans la branche develop.
Je ne suis pas certain que cette PR corresponde exactement à ce que vous souhaitez pousser.

Quels sont les fichiers que vous avez modifié dans votre branche initial ?

2023-04-07 13:45 UTC, Gaetanbrl requested changes
Trop de ressources en conflit.
Un rebase à réaliser sur la branche contenant les modifications ?

2023-04-11 14:57 UTC, Gaetanbrl commented
@Agath21 une petite revue css stp ? :)

2023-07-04 13:48 UTC, Gaetanbrl commented on js/templates.js
> -                    'data-target="#loginpanel"',
Attention, l'éditeur semble avoir des règles spécifiques pour le format.

2023-07-05 08:05 UTC, lecault commented
Je viens de tester le fonctionnement de cette issue.
J'ai bien le +/- qui apparaît mais dans mon cas il n'est pas utile :
![image](https://github.com/mviewer/mviewer/assets/5269430/cb348215-e83d-4c4e-86d3-698f2e8dc344)

Quel paramétrage faut t'il pour avoir les entités à la suite ? J'ai essayé avec l'option templatebottominfopanel sans succès.

2023-07-05 09:11 UTC, Gaetanbrl commented
Question pour @bdavid-rennesmetrpole je suppose @lecault ?

2023-07-05 09:16 UTC, lecault commented
> Question pour @bdavid-rennesmetrpole je suppose @lecault ?

oui

2023-07-05 12:48 UTC, bdavid-rennesmetrpole commented
Avec un navigateur paramétré en mode "mobile", sur la carte "demo/addlayers.xml", activer les couches des lycées et des arrêts régionaux.
Vous aurez une interface qui permet de tester et qui sera équivalente à l'interface suivante
![Capture](https://github.com/mviewer/mviewer/assets/85627821/6329bcdc-bd89-4d9e-bde4-f8d6fc728cbd)

2023-07-06 11:45 UTC, lecault commented
Ok pour le fonctionnel, reste la remarque de @Gaetanbrl sur le code pour valider la PR

2023-07-06 14:29 UTC, Gaetanbrl commented
@lecault c'est bon pour moi

2023-07-06 16:01 UTC, merged