Amélioration de l'impression depuis un navigateur
mviewer/mviewer pull request #812
Opened 2023-10-30 16:01 UTC by Agath21

Cette contribution propose les modifications suivantes : 
- Optimisation du style lors de l'impression via une nouvelle feuille de style spécifique `print.css` #793 
- Création d'un nouveau paramètre `mapprint` permettant d'imprimer la vue courante depuis le navigateur #811 
- Activation de la nouvelle fonctionnalité dans l'application par défaut `apps/defaut.xml`
- Mise à jour de la documentation et des traductions (i18n)

Ne parlant pas allemand, ni slovaque la traduction est basée sur un traducteur, n'hésitez donc pas à me proposer une amélioration en cas d'erreur :) 

## Tests à réaliser : 

- [ ] Activation du paramètre `mapprint` = affichage du bouton dans l'interface
- [ ] Ouverture de la fenêtre d'impression lors du clic 
- [ ] Affichage de la carte et de la légende
- [ ] Affichage du `#right-panel` en cas d'interrogation d'une entité
- [ ] Affichage du `#bottom-panel` en cas d'interrogation d'une entité

2023-11-06 15:10 UTC, Gaetanbrl commented
Testé avec affichage indépendant et simultané du right et bottom panel => OK pour moi.
L'impression est plus exploitable via le navigateur avec cette PR. Merci @Agath21 👍 !

![image](https://github.com/mviewer/mviewer/assets/16317988/0065f069-6dd8-467d-bbcc-bcd000f9f64d)

2023-11-06 15:18 UTC, Gaetanbrl approved these changes
LGTM

2023-11-08 13:44 UTC, lecault reviewed
Hello, merci pour le dev.

Quelques remarques mineures ne nécessitant pas forcément de modifications :
- En lien avec la remarque sur CORS dans l'export PNG (cf doc) j'ai cherché un cas où ça ne fonctionne pas, j'ai pas trouvé.
- La partie carte ne pourrait t'elle pas prend plus de place en bas ? Je trouve qu'il y a un trop gros espace.
- Le pied de page "Propulsé par mviewer (https://mviewer.netlify.app/fr/) 3.10-snapshot" me semble trop imposant.
- En impression mobile, le résultat est moins bon

2023-11-10 08:47 UTC, lecault commented
Ah oui je valide même si mes remarques ne sont pas prises en compte. C'est du facultatif :).
Le seul qui nécessite enquête pour moi est l'espace blanc entre la carte et la source.
Pour le mobile je pense que ce n'est pas utilisé.

2023-11-20 13:53 UTC, lecault commented
Ici : 

![image](https://github.com/mviewer/mviewer/assets/5269430/1442768b-cc9e-4ec9-a274-877d6c666d65)

2023-11-20 14:46 UTC, Gaetanbrl commented
A voir avec @Agath21 mais en regardant le code j'ai l'impression que ce blanc est obligatoire pour conserver les ratio de la carte.
sinon la carte sera déformée je pense.

2023-11-21 15:15 UTC, Agath21 commented
> Ici :
> 
> ![image](https://user-images.githubusercontent.com/5269430/284286603-1442768b-cc9e-4ec9-a274-877d6c666d65.png)

L'affichage varie selon les navigateurs, je ne reproduis pas ce problème sous Mozilla. J'a

2023-11-21 15:29 UTC, lecault commented
Merci Agathe.

Je viens de tester on a effet de bord, le cadrage de la carte n'est pas bon.

Exemple sur le default sans changer la vue : 

![image](https://github.com/mviewer/mviewer/assets/5269430/a0e7c23b-7c59-436a-8b78-620639769b90)

2023-11-21 15:56 UTC, Gaetanbrl commented
> Je viens de tester on a effet de bord, le cadrage de la carte n'est pas bon.

Je pense que le cadrage de la carte ne correspond pas au format (e.g A4). Donc quand on ouvre la boîte de dialogue d'impression, le navigateur (qui est l'outil utilisé) va faire s'arranger du cadrage qui correspond au A4.

En reprenant la carte par défaut, si on change la div #map en forçant le A4 (297mm x 210mm) on a bien le même cadrage que la boîte de dialogue du navigateur : 

![image](https://github.com/mviewer/mviewer/assets/16317988/5dcc5e7a-e5a4-47f7-9a93-9ded7072912d)

![image](https://github.com/mviewer/mviewer/assets/16317988/2c16a6ca-6365-4f1b-8f3f-11ee3fabee97)


Si on souhaite avoir un cadrage "carré" avec les formats de la boîte de dialogue, alors il faut utiliser le plugin "print" ou bien prévoir de modifier la taille de la map (via une UI supplémentaire) pour avoir un format identique au format d'impression. Sinon on aura toujours un décalage entre la carte (selon les écrans qui plus est) et la boite de dialogue qui réduit la div de la map au format chois (e.g A4).

2023-11-21 16:02 UTC, Agath21 commented
Du coup j'ai supprimé la propriété, je laisse en l'état car je ne souhaite pas surchargé le css avec des propriétés supplémentaires ou du javascript pour refresh la carte (comme le plugin). L'utilisateur pourra régler l'impression avec les paramètres du navigateur (format, marges, mise à l'échelle et divers options).

2023-11-22 08:13 UTC, Gaetanbrl commented
@lecault je viens de vérifier et le rendu avant cette PR intégré une bande blanche et un cadrage aussi erroné (et d'autres élément non désirables).

![image](https://github.com/mviewer/mviewer/assets/16317988/26978302-c84b-4cd7-90a6-6e570ed48fdc)

Je propose de merger cette PR (qui améliore le rendu dans la boite d'impression dans tous les cas...). En sachant qu'on a le plugin d'impression qui donne de bien meilleur résultat.

2023-11-22 09:36 UTC, Gaetanbrl commented
@Agath21 je m'affecte la PR pour corriger le conflit avec le index.html que j'ai du apporté via ma dernière PR avec OL8 (j'ai du passer du formatage dans le html...).

2023-11-24 07:34 UTC, Gaetanbrl requested changes
pour moi-même - corriger le conflit index.html

2023-11-24 10:47 UTC, Gaetanbrl approved these changes
Conflit géré.

2023-11-24 10:48 UTC, merged