Mviewer#764 masquer une couche et url courte
mviewer/mviewer pull request #897
Opened 2024-07-04 14:14 UTC by pbarille

Bonjour,

Voici une proposition de résolution de l'issue #764 

J'ai modifié le configuration.js pour que lorsqu'il y a un "raccourci" de créé dans le mviewer via le "#", il soit maintenu lors du clic sur le titre ou sur le logo.

J'ai modifié le template.js pour que de la même manière il soit maintenu quand il existe à l'affichage/masquage d'une couche.

J'ai également modifié le gitignore pour que les xml publiés dans le dossier apps ne soient pas pris en compte. Sachant que dans les fait j'utilise un lien symbolique entre le dossier apps et mes dossier apps/application de manière à bénéficier du raccourci tout en gérant tous les fichiers de l'application dans le dossier dédié.

D'avance merci pour votre retour sur la proposition !
Bonne journée,

Pascal

2024-07-04 19:45 UTC, pbarille commented on .gitignore
> +!apps/settings.json
Effectivement c'est une erreur.
Est-ce que si on garde apps/* et !apps/defaut.xml cela conviendrait ?
Mon objectif principal était de ne pas remonter les liens symboliques en .xml

2024-07-04 19:46 UTC, pbarille commented on js/templates.js
> +if (location.hash){
Effectivement c'est beaucoup plus propre, merci !

2024-07-05 06:34 UTC, Gaetanbrl commented on .gitignore
> +!apps/settings.json
> Mon objectif principal était de ne pas remonter les liens symboliques en .xml

Cela revient également à ignorer toutes modifications d'un .xml même si ce n'est pas un symlink.
C'est vrai qu'en dehors du default.xml utilisé en exemple, le /apps est un répertoire custom qui n'a pas vocation a être détecté par le dépôt core mviewer.

Donc on peut ignorer les XML.

Par contre la règle `apps/*` permet de tout ignorer dans `/apps`, donc pour moi ca devrait suffir (`!apps/default.xml` et `!apps/settings.json` sont donc inutiles). Si tu ne laisse que `/apps` est-ce que ca convient aussi ?

2024-07-05 07:00 UTC, pbarille commented on .gitignore
> +!apps/settings.json
Oui ça me va aussi !
Je fais la modif dans la PR

2024-07-05 07:03 UTC, Gaetanbrl approved these changes
Ça me semble bon.
Merci @pbarille

2024-07-05 07:04 UTC, Gaetanbrl commented
Par contre @pbarille je suis surpris de voir autant de commit dans la PR : 

![image](https://github.com/mviewer/mviewer/assets/16317988/95068686-6520-4e47-a98b-2e0f0564a478)

2024-07-05 07:06 UTC, Gaetanbrl commented
> Par contre @pbarille je suis surpris de voir autant de commit dans la PR :

Je pense avoir compris.

J'ai l'impression que tu est parti de la branche master pour y faire tes modifications et qu'ensuite tu as ciblé la branche develop pour faire ta pull request.

C'est cela @pbarille ?

2024-07-05 07:07 UTC, Gaetanbrl requested changes
La branche source ne semble pas correct.

2024-07-05 07:12 UTC, pbarille commented
Oui je suis parti de la branche master pour faire mes modifications et j'ai ciblé la branche develop.
Ce n'est pas comme ça qu'il faut procéder ?

2024-07-05 07:41 UTC, Gaetanbrl commented
> Ce n'est pas comme ça qu'il faut procéder ?

En effet pour cibler une branche, il faut repartir de la même branche.

Le flow est le suivant : 

1. on part de develop
2. on rajoute ses modifications
3. on pousse dans develop via une contribution
4. Plus tard, l'ensemble des modifications / contributions de develop sont versées (merge) dans la branche master (c'est une release)

Ce process assure que master contient toutes les modifications de develop et que les branches ne divergent pas.

Ce process est décrit dans la partie contribution (flow) de la doc mais ce n'est peut être pas clair pour savoir à partir de quelle branche partir.

https://mviewerdoc.readthedocs.io/fr/stable/doc_contrib/git.html#presentation-git-flow

2024-07-05 07:45 UTC, pbarille commented
> > Ce n'est pas comme ça qu'il faut procéder ?
> 
> En effet pour cibler une branche, il faut repartir de la même branche.
> 
> Le flow est le suivant :
> 
>     1. on part de develop
> 
>     2. on rajoute ses modifications
> 
>     3. on pousse dans develop via une contribution
> 
>     4. Plus tard, l'ensemble des modifications / contributions de develop sont versées (merge) dans la branche master (c'est une release)
> 
> 
> Ce process assure que master contient toutes les modifications de develop et que les branches ne divergent pas.
> 
> Ce process est décrit dans la partie contribution (flow) de la doc mais ce n'est peut être pas clair pour savoir à partir de quelle branche partir.
> 
> https://mviewerdoc.readthedocs.io/fr/stable/doc_contrib/git.html#presentation-git-flow

Ok, désolé pour la fausse manip.
Je ferme cette PR et j'en recrée une ?

2024-07-05 07:47 UTC, Gaetanbrl commented
Tu peux me contacter sur Element ?

2024-07-05 07:56 UTC, Gaetanbrl commented
Pour repartir de develop à jour tu peux utiliser ces commandes git : 

```
git remote add upstream https://github.com/mviewer/mviewer.git
git fetch upstream
git reset --hard upstream/develop
git cherry-pick ce657c4be3c1ce96bd650bf67bcd99d8117c6956
git cherry-pick 55f7209535633909c8d15329a0ea005cd147941e
git cherry-pick fe8a0c982c761719a02598f4ec63a515bea22d7e
git cherry-pick 6d424cb53f787eaafefc853f63a7df9e72aff992
git cherry-pick 294a2bbbf037c0f77a6e540299711fe888480b3b
git cherry-pick 093dad3a905e82cc792c13b8afdf002b61ebfa10
git push -f
```

2024-07-05 08:07 UTC, pbarille commented
J'ai tout géré directement sur github vu qu'il n'y avait pas beaucoup de modifications.
je ne suis pas sûr de pouvoir passer ce type de commande dans l'interface web, si ?
J'ai tenté de te contacter sur element mais peut être n'ai je pas ciblé ton bon identifiant ? (j'ai pris ton id github)
Tout est prêt sur une nouvelle branche que j'ai créée, basée sur develop cette fois. Ce n'est pas plus simple de regénérer une PR ?

Merci !

2024-07-05 08:12 UTC, Gaetanbrl commented
Il faut passer les commandes dans le terminal en effet.

Mon ID GitHub Element @gaetanbrl:matrix.org

2024-07-05 08:23 UTC, closed without merging