Modification de la documentation pour les outils avancés
mviewer/mviewer pull request #921
Opened 2024-10-21 10:13 UTC by raphael-dsc

2024-10-22 08:48 UTC, lecault commented
Problème sur cette PR : sans doute basée sur la branche master

2024-10-28 10:48 UTC, Gaetanbrl commented
La PR contient des commits d'autres users.
Est-ce normal ?

2024-10-28 10:49 UTC, Gaetanbrl requested changes
La branche de départ ne semble pas correcte.
Idem pour la branche cible qui ne devrait pas pointer vers master mais develop.

Voir :
https://mviewerdoc.readthedocs.io/fr/stable/doc_contrib/git.html#presentation-git-flow

2024-10-30 13:39 UTC, closed without merging

2024-10-30 13:39 UTC, raphael-dsc commented
Mauvaise branche de départ. PR à refaire